name: xinthink's blog
description: personal blog of xinthink
url: http://xinthink.com
safe: false
lsi: false
auto: true
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  render_options:
    - with_toc_data
    - hard_wrap